# Will use the latest image of nginx from Docker Hub. This is the official nginx image
FROM nginx:latest

# Will copy the contents of our app to the default html folder of our container
COPY app /usr/share/nginx/html